# Generated by Django 2.2.5 on 2019-09-13 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import labs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=labs.models.current_year)),
                ('semester', models.IntegerField(choices=[(1, 'Sem1'), (2, 'Sem2')], default=(2, 'Sem2'))),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='labs.Course')),
                ('instructors', models.ManyToManyField(related_name='labs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matric_num', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('face_encoding', models.TextField(max_length=500)),
                ('labs', models.ManyToManyField(related_name='students', to='labs.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('session_time', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='labs.Lab')),
            ],
            options={
                'ordering': ('session_time',),
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Attended'), ('L', 'Late'), ('AB', 'Absence without valid reasons'), ('MC', 'Missing with valid reasons')], default='AB', max_length=2)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Student')),
            ],
        ),
    ]
